//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeckMan.Del
{
    using System;
    using System.Collections.Generic;
    
    public partial class bec_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bec_User()
        {
            this.bec_PartionSet = new HashSet<bec_Partion>();
        }
    
        public int Id { get; set; }
        public string UserNo { get; set; }
        public string UserName { get; set; }
        public string RoleType { get; set; }
        public string IsDistributor { get; set; }
        public string Activity { get; set; }
        public string UserCode { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bec_Partion> bec_PartionSet { get; set; }
    }
}
