//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeckMan.Del
{
    using System;
    using System.Collections.Generic;
    
    public partial class bec_ProFile
    {
        public int Id { get; set; }
        public string DisNo { get; set; }
        public string DisName { get; set; }
        public string PName { get; set; }
        public string OperName { get; set; }
        public string ProName { get; set; }
        public string FileUrl { get; set; }
        public System.DateTime PutDate { get; set; }
    }
}
