//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeckMan.Del
{
    using System;
    using System.Collections.Generic;
    
    public partial class bec_Aear
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bec_Aear()
        {
            this._bec_AssInformation = new HashSet<bec_AssInformation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Remak { get; set; }

        [NonSerialized]
        private ICollection<bec_AssInformation> _bec_AssInformation;

        public virtual ICollection<bec_AssInformation> bec_AssInformation {
            get { return _bec_AssInformation; }
            set { _bec_AssInformation = value; }
        }
    }
}
