//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeckMan.Del
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeckManEntities : DbContext
    {
        public BeckManEntities()
            : base("name=BeckManEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bes_user> bes_userSet { get; set; }
        public virtual DbSet<bec_Aear> bec_AearSet { get; set; }
        public virtual DbSet<bec_Partion> bec_PartionSet { get; set; }
        public virtual DbSet<bec_AssInformation> bec_AssInformationSet { get; set; }
        public virtual DbSet<bec_Role> bec_RoleSet { get; set; }
        public virtual DbSet<bec_Product> bec_ProductSet { get; set; }
    }
}
